### ISSUE TITLE
Tabs sometimes fall out of tab groups

### ISSUE THREAD

**Issue by mbetrifork** [mbnuqw/sidebery#524]
## Steps to reproduce
I can't describe how to reproduce the issue because it is not consistent. 

## Expected behavior
Tabs stay in groups.

## Actual behavior
What happens is that I have the Sidebery panel open in Firefox with a bunch of tabs in, many of them grouped in tab groups. I can't seem to find consistent patttern to it, but sometimes when I startup Firefox all the tabs that were in groups appear outside of the groups (on the top level), and all the folder groups are empty. They still exist but they have no tabs in them.

I have a vague suspicion that this might be caused by me having Firefox on two computers and that Firefox' synchronization is somehow interfering with Sidebery. I don't use tab synchronization so it shouldn't be affecting anything but it might be worth looking into.

## Environment info
OS:  
michael@michael-Latitude-5511:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.10
Release:	21.10
Codename:	impish

Firefox version:  
Version 94.0.2 (64-bit)
Mozilla Firefox Snap for Ubuntu

Addon version:  

<details><code>
{
  "settings": {
    "version": "4.9.4",
    "nativeScrollbars": false,
    "selWinScreenshots": true,
    "tabsCheck": true,
    "tabsFix": "notify",
    "markWindow": false,
    "markWindowPreface": "[Sidebery] ",
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": true,
    "ctxMenuIgnoreContainers": "",
    "navBarLayout": "horizontal",
    "navBarInline": false,
    "hideAddBtn": false,
    "hideSettingsBtn": false,
    "navBtnCount": true,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "skipEmptyPanels": false,
    "dndTabAct": true,
    "dndTabActDelay": 750,
    "dndTabActMod": "none",
    "dndExp": "pointer",
    "dndExpDelay": 0,
    "dndExpMod": "none",
    "stateStorage": "global",
    "warnOnMultiTabClose": "collapsed",
    "activateOnMouseUp": true,
    "activateLastTabOnPanelSwitching": true,
    "showTabRmBtn": true,
    "showTabCtx": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "activateAfterClosingGlobal": false,
    "activateAfterClosingNoFolded": true,
    "activateAfterClosingNoDiscarded": true,
    "shiftSelAct": true,
    "askNewBookmarkPlace": false,
    "tabsRmUndoNote": true,
    "nativeHighlight": false,
    "tabsUnreadMark": false,
    "tabsReloadLimit": 5,
    "tabsReloadLimitNotif": true,
    "moveNewTabPin": "start",
    "moveNewTabParent": "last_child",
    "moveNewTabParentActPanel": false,
    "moveNewTab": "end",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "pinnedAutoGroup": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoFoldTabsExcept": "none",
    "autoExpandTabs": true,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "tabsTreeBookmarks": true,
    "treeRmOutdent": "branch",
    "bookmarksPanel": false,
    "warnOnMultiBookmarkDelete": "collapsed",
    "openBookmarkNewTab": false,
    "midClickBookmark": "open_new_tab",
    "actMidClickTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "bookmarksRmUndoNote": true,
    "fontSize": "l",
    "bgNoise": true,
    "animations": true,
    "animationSpeed": "fast",
    "theme": "default",
    "style": "auto",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapNotify": true,
    "snapExcludePrivate": false,
    "snapInterval": 0,
    "snapIntervalUnit": "min",
    "snapLimit": 0,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsSkipDiscarded": false,
    "scrollThroughTabsExceptOverflow": true,
    "scrollThroughTabsCyclic": false,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "menu",
    "tabsPanelMiddleClickAction": "tab",
    "syncName": "",
    "syncSaveSettings": true,
    "syncSaveCtxMenu": false,
    "syncSaveStyles": false,
    "syncAutoApply": false
  },
  "permissions": {
    "allUrls": false,
    "tabHide": false,
    "actualAllUrls": false,
    "actualTabHide": false
  },
  "storage": {
    "size": "135.8 kb",
    "props": {
      "containers_v4": "798 b",
      "expandedBookmarks": "2 b",
      "favAutoCleanTime": "10 b",
      "favUrls": "1.6 kb",
      "favicons": "128.7 kb",
      "panelIndex": "1 b",
      "panels_v4": "775 b",
      "prevTabsData_v4": "535 b",
      "profileID": "14 b",
      "settings": "2.7 kb",
      "tabsData_v4": "473 b"
    }
  },
  "panels": [
    {
      "type": "bookmarks",
      "id": "bookmarks",
      "cookieStoreId": "bookmarks",
      "name": 9,
      "icon": "...",
      "bookmarks": true,
      "lockedPanel": false,
      "skipOnSwitching": false
    },
    {
      "type": "default",
      "id": "firefox-default",
      "name": 7,
      "icon": "...",
      "cookieStoreId": "firefox-default",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true
    },
    {
      "type": "tabs",
      "id": "DVgQTARi5YUZ",
      "name": 11,
      "icon": "...",
      "color": "...",
      "customIconSrc": "",
      "customIcon": "",
      "lockedTabs": false,
      "lockedPanel": false,
      "skipOnSwitching": false,
      "noEmpty": false,
      "newTabCtx": "none",
      "dropTabCtx": "none",
      "moveTabCtx": "none",
      "moveTabCtxNoChild": true,
      "urlRulesActive": false,
      "urlRules": ""
    }
  ],
  "containers": [
    {
      "id": "firefox-container-1",
      "name": 8,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-2",
      "name": 4,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    },
    {
      "id": "firefox-container-6",
      "name": 14,
      "icon": "...",
      "color": "...",
      "proxified": false,
      "proxy": null,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "userAgentActive": false,
      "userAgent": ""
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 34
    }
  ],
  "bookmarks": {
    "bookmarksCount": 910,
    "foldersCount": 66,
    "separatorsCount": 1,
    "maxDepth": 4
  }
}
</code></details>

**Comment by z15900** [comment]
I'm having the exact same issue. I'm using Firefox on a single PC running Windows 11. It's happened to me at least 3 times - I've had Sidebery installed for about 1 month.

It always seems to rear its head when FF is restarted. The default/first group has all the tabs and the others are completely emptied.

I wonder if it's got something to do with Firefox running out of memory. This time prior to it happening I was getting PR_END_OF_FILE_ERROR on some websites I was trying to visit, so restarted FF (which fixed that issue but broke Sidebery).

**Comment by randywallace** [comment]
When this happens to me, I usually restore the window from a previous snapshot, at which point it will come back fine a second time, if that helps

**Comment by megamorphg** [comment]
But why would we use session storage?
"But this file is temporary and is deleted from the file-system when the browser is closed or the user navigates somewhere else."
-- https://smartmobilestudio.com/documentation/getting-started/local-storage-session-storage-and-global-storage/

**Comment by mbnuqw** [comment]
Should be fixed in the latest version.

**Comment by Clawhed** [comment]
**Windows Version 10.0.19045.5371 64-bit**
**Firefox v134.0.2**
**Sidebery v5.2.0**

Hello, unfortunately I'm still experiencing aforementioned problem. I read through this post but found that there is no option to switch between global and session storage anymore. Every now and then after launching Firefox I find that all tabs are merged into the first group. This nuisance used to be solvable by loading an earlier snapshot. But yesterday I found that although all my tabs are still there, grouping isn't restored anymore. Any ideas on how to fix that?
