### ISSUE TITLE
Tabs are completely lost sometimes

### ISSUE THREAD

**Issue by snowe2010** [mbnuqw/sidebery#86]
This picture demonstrates the problem

<img width="220" alt="Screen Shot 2019-09-10 at 11 30 12 AM" src="https://user-images.githubusercontent.com/1534535/64636263-947d5700-d3be-11e9-981d-74bdb3d8ef0c.png">

There are 19 tabs here, but only 18 are shown. Not only that, but I've closed that last tab, `Sidebery / Debug`, but it still shows up in the list and is not selectable anymore. I can only access the 19th tab by using Vimium and moving to the next tab from the 17th tab.

**Comment by mbnuqw** [comment]
Thanks for reporting. Can you provide steps to reproduce and the list of used extensions?

**Comment by snowe2010** [comment]
Not sure how to reproduce, it happens pretty randomly. I have over 1000 tabs so that might be partially the reason. Is there an easy way to retrieve the list of extensions? I have quite a lot.

**Comment by mbnuqw** [comment]
Help > Troubleshooting Information
The "Extensions" section.

**Comment by snowe2010** [comment]
```json
{
  "extensions": [
    {
      "name": "Amazon.com",
      "version": "1.1",
      "isActive": true,
      "id": "amazondotcom@search.mozilla.org"
    },
    {
      "name": "Bing",
      "version": "1.0",
      "isActive": true,
      "id": "bing@search.mozilla.org"
    },
    {
      "name": "Dark Mode",
      "version": "0.3.4",
      "isActive": true,
      "id": "{174b2d58-b983-4501-ab4b-07e71203cb43}"
    },
    {
      "name": "DuckDuckGo",
      "version": "1.0",
      "isActive": true,
      "id": "ddg@search.mozilla.org"
    },
    {
      "name": "eBay",
      "version": "1.0",
      "isActive": true,
      "id": "ebay@search.mozilla.org"
    },
    {
      "name": "Firefox Color",
      "version": "2.1.5",
      "isActive": true,
      "id": "FirefoxColor@mozilla.com"
    },
    {
      "name": "Firefox Multi-Account Containers",
      "version": "6.1.0",
      "isActive": true,
      "id": "@testpilot-containers"
    },
    {
      "name": "Form Filler",
      "version": "2.10.3",
      "isActive": true,
      "id": "{7efbd09d-90ad-47fa-b91a-08c472bdf566}"
    },
    {
      "name": "Gecko Profiler",
      "version": "0.30",
      "isActive": true,
      "id": "geckoprofiler@mozilla.com"
    },
    {
      "name": "Google",
      "version": "1.0",
      "isActive": true,
      "id": "google@search.mozilla.org"
    },
    {
      "name": "LastPass: Free Password Manager",
      "version": "4.31.2.3",
      "isActive": true,
      "id": "support@lastpass.com"
    },
    {
      "name": "Octotree",
      "version": "3.0.8",
      "isActive": true,
      "id": "jid1-Om7eJGwA1U8Akg@jetpack"
    },
    {
      "name": "Reddit Enhancement Suite",
      "version": "5.16.10",
      "isActive": true,
      "id": "jid1-xUfzOsOFlzSOXg@jetpack"
    },
    {
      "name": "Reddit Masstagger",
      "version": "1.2.3.3",
      "isActive": true,
      "id": "{5e1c12e6-57bf-448f-be3c-579688023809}"
    },
    {
      "name": "Refined GitHub",
      "version": "19.9.9",
      "isActive": true,
      "id": "{a4c4eda4-fb84-4a84-b4a1-f7c1cbf2a1ad}"
    },
    {
      "name": "Sidebery",
      "version": "3.0.5",
      "isActive": true,
      "id": "{3c078156-979c-498b-8990-85f7987dd929}"
    },
    {
      "name": "Stylus",
      "version": "1.5.5",
      "isActive": true,
      "id": "{7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}"
    },
    {
      "name": "To Google Translate",
      "version": "3.10",
      "isActive": true,
      "id": "jid1-93WyvpgvxzGATw@jetpack"
    },
    {
      "name": "Twitter",
      "version": "1.0",
      "isActive": true,
      "id": "twitter@search.mozilla.org"
    },
    {
      "name": "uBlock Origin",
      "version": "1.22.2",
      "isActive": true,
      "id": "uBlock0@raymondhill.net"
    },
    {
      "name": "uMatrix",
      "version": "1.4.0",
      "isActive": true,
      "id": "uMatrix@raymondhill.net"
    },
    {
      "name": "Vimium",
      "version": "1.64.6",
      "isActive": true,
      "id": "{d7742d87-e61d-4b78-b8a1-b469842139fa}"
    },
    {
      "name": "Wikipedia (en)",
      "version": "1.0",
      "isActive": true,
      "id": "wikipedia@search.mozilla.org"
    },
    {
      "name": "Adobe Acrobat",
      "version": "18.0.10",
      "isActive": false,
      "id": "web2pdfextension.17@acrobat.adobe.com"
    },
    {
      "name": "CanvasBlocker",
      "version": "0.5.13",
      "isActive": false,
      "id": "CanvasBlocker@kkapsner.de"
    },
    {
      "name": "Firefox Pioneer",
      "version": "1.0",
      "isActive": false,
      "id": "pioneer-opt-in@mozilla.org"
    },
    {
      "name": "Violentmonkey",
      "version": "2.11.2",
      "isActive": false,
      "id": "{aecec67f-0d10-4fa7-b7c7-609a2db280cf}"
    }
  ],
  "features": [
    {
      "name": "Firefox Monitor",
      "version": "3.0",
      "id": "fxmonitor@mozilla.org"
    },
    {
      "name": "Firefox Screenshots",
      "version": "39.0.0",
      "id": "screenshots@mozilla.org"
    },
    {
      "name": "Form Autofill",
      "version": "1.0",
      "id": "formautofill@mozilla.org"
    },
    {
      "name": "Web Compat",
      "version": "5.0.2",
      "id": "webcompat@mozilla.org"
    },
    {
      "name": "WebCompat Reporter",
      "version": "1.1.0",
      "id": "webcompat-reporter@mozilla.org"
    }
  ]
} 
```

**Comment by mbnuqw** [comment]
Thanks.

**Comment by snowe2010** [comment]
this bug is extremely consistent for me, happening every few tabs. If there is any other information I can provide, debug logs, etc. let me know and I will.

**Comment by mbnuqw** [comment]
Sorry for the delay. Can you provide steps to reproduce and debug info JSON (from Settings/Debug)? I'll try to check this later today.

**Comment by snowe2010** [comment]
Oh I thought I had responded to this. I do not really have steps to reproduce, besides open a ton of tabs and then middle click links in a webpage to try to open in a separate tab. Sometimes they just won't show in the pane. It also seems to 'mess up' the order of stuff. So if I close a tab then it might jump to a different Container. 

<details>
<summary>Details</summary>

<pre>
{
  "settings": {
    "version": "3.1.1",
    "nativeScrollbars": false,
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": false,
    "navBarInline": true,
    "hideSettingsBtn": false,
    "navBtnCount": false,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "bookmarksPanel": true,
    "openBookmarkNewTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "theme": "default",
    "style": "dark",
    "sidebarCSS": false,
    "groupCSS": false,
    "snapInterval": 20,
    "snapIntervalUnit": "min",
    "snapLimit": 2,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsExceptOverflow": true,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "none"
  },
  "permissions": {
    "allUrls": true,
    "tabHide": false,
    "actualAllUrls": true,
    "actualTabHide": false
  },
  "storage": {
    "size": "2.4 mb",
    "props": {
      "favAutoCleanTime": "10 b",
      "favUrls": "62.7 kb",
      "favicons": "1.9 mb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels": "1.9 kb",
      "prevTabsTrees": "30.5 kb",
      "settings": "1.4 kb",
      "snapshots": "310.3 kb",
      "tabsTrees": "26.7 kb"
    }
  },
  "panels": [
    {
      "icon": "...",
      "name": 9,
      "type": "bookmarks",
      "id": "bookmarks",
      "dashboard": "BookmarksDashboard",
      "panel": "BookmarksPanel",
      "lockedPanel": false,
      "bookmarks": true
    },
    {
      "cookieStoreId": "firefox-private",
      "icon": "...",
      "name": 7,
      "type": "private",
      "id": "firefox-private",
      "dashboard": "DefaultTabsDashboard",
      "panel": "TabsPanel",
      "private": true
    },
    {
      "cookieStoreId": "firefox-default",
      "icon": "...",
      "name": 7,
      "type": "default",
      "id": "firefox-default",
      "dashboard": "DefaultTabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false,
      "lastActiveTab": 1007
    },
    {
      "cookieStoreId": "firefox-container-1",
      "colorCode": "#37adff",
      "color": "...",
      "icon": "...",
      "iconUrl": "resource://usercontext-content/fingerprint.svg",
      "name": 8,
      "type": "ctx",
      "id": "firefox-container-1",
      "dashboard": "TabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "lastActiveTab": 963
    },
    {
      "cookieStoreId": "firefox-container-2",
      "colorCode": "#ff9f00",
      "color": "...",
      "icon": "...",
      "iconUrl": "resource://usercontext-content/briefcase.svg",
      "name": 4,
      "type": "ctx",
      "id": "firefox-container-2",
      "dashboard": "TabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "lastActiveTab": 529
    },
    {
      "cookieStoreId": "firefox-container-6",
      "colorCode": "#af51f5",
      "color": "...",
      "icon": "...",
      "iconUrl": "resource://usercontext-content/cart.svg",
      "name": 9,
      "type": "ctx",
      "id": "firefox-container-6",
      "dashboard": "TabsDashboard",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": "",
      "lastActiveTab": 1113
    }
  ],
  "cssVars": "TypeError: can't convert undefined to object",
  "windows": [
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 370,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 45,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 2,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 16,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 4,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 3,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "maximized",
      "incognito": false,
      "tabsCount": 427,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs order was normalized",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 5,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    }
  ],
  "bookmarks": {
    "bookmarksCount": 413,
    "foldersCount": 25,
    "separatorsCount": 2,
    "maxDepth": 3
  }
}
</pre>

</details>

**Comment by mbnuqw** [comment]
I think I found the root of this problem! Can you go to the settings, section "Storage" and then delete property "panels"?
note: This will reset some of the panels configs (like proxy/include-exclude rules/lock), but containers itself and tabs will not be touched.

**Comment by snowe2010** [comment]
Ok! I've done so. I'll let you know if I see the issue come up in the next day or so.

**Comment by snowe2010** [comment]
Sorry, I went on vacation immediately after posting that comment. I haven't seen the issue though so I think that fixed it! Do you mind explaining what the actual issue was?

**Comment by mbnuqw** [comment]
I think the issue was related to saving the private panel info (normally it should store only 'firefox-default' panel). I've fixed this in ~v3.0.x/maybe in v3.1.0, but I forgot to check already saved info and fix it in place on upgrade.

I'll close this issue, but if it appears again (maybe the cause is different), please reopen it.

**Comment by snowe2010** [comment]
Dang, the issue is back. Should I just delete the property 'panels' again?

**Comment by mbnuqw** [comment]
Can you post debug info again?

**Comment by snowe2010** [comment]
<details>
<summary>Details</summary>

<pre>
{
  "settings": {
    "version": "3.1.1",
    "nativeScrollbars": false,
    "ctxMenuNative": false,
    "autoHideCtxMenu": "none",
    "ctxMenuRenderInact": false,
    "navBarInline": true,
    "hideSettingsBtn": false,
    "navBtnCount": false,
    "hideEmptyPanels": true,
    "navMidClickAction": "none",
    "navSwitchPanelsWheel": true,
    "groupLayout": "grid",
    "activateOnMouseUp": false,
    "activateLastTabOnPanelSwitching": true,
    "skipEmptyPanels": false,
    "showTabRmBtn": true,
    "hideInact": false,
    "activateAfterClosing": "next",
    "activateAfterClosingPrevRule": "visible",
    "activateAfterClosingNextRule": "tree",
    "pinnedTabsPosition": "panel",
    "pinnedTabsList": false,
    "tabsTree": true,
    "groupOnOpen": true,
    "tabsTreeLimit": "none",
    "hideFoldedTabs": false,
    "autoFoldTabs": false,
    "autoExpandTabs": false,
    "rmChildTabs": "none",
    "tabsChildCount": true,
    "tabsLvlDots": false,
    "discardFolded": false,
    "discardFoldedDelay": 0,
    "discardFoldedDelayUnit": "sec",
    "bookmarksPanel": true,
    "openBookmarkNewTab": false,
    "autoCloseBookmarks": false,
    "autoRemoveOther": false,
    "highlightOpenBookmarks": false,
    "activateOpenBookmarkTab": false,
    "showBookmarkLen": false,
    "fontSize": "m",
    "bgNoise": true,
    "animations": true,
    "theme": "default",
    "style": "dark",
    "sidebarCSS": true,
    "groupCSS": false,
    "snapInterval": 20,
    "snapIntervalUnit": "min",
    "snapLimit": 2,
    "snapLimitUnit": "snap",
    "hScrollThroughPanels": false,
    "scrollThroughTabs": "none",
    "scrollThroughVisibleTabs": false,
    "scrollThroughTabsExceptOverflow": true,
    "tabDoubleClick": "none",
    "tabLongLeftClick": "none",
    "tabLongRightClick": "none",
    "tabsPanelLeftClickAction": "none",
    "tabsPanelDoubleClickAction": "tab",
    "tabsPanelRightClickAction": "none"
  },
  "permissions": {
    "allUrls": true,
    "tabHide": false,
    "actualAllUrls": true,
    "actualTabHide": false
  },
  "storage": {
    "size": "2.5 mb",
    "props": {
      "cssVars": "1.6 kb",
      "favAutoCleanTime": "10 b",
      "favUrls": "74.6 kb",
      "favicons": "2.1 mb",
      "lastSnapTime": "13 b",
      "panelIndex": "1 b",
      "panels": "1.1 kb",
      "prevTabsTrees": "18.4 kb",
      "settings": "1.4 kb",
      "sidebarCSS": "33 b",
      "snapshots": "307.9 kb",
      "tabsTrees": "16 kb"
    }
  },
  "panels": [
    {
      "cookieStoreId": "bookmarks",
      "icon": "...",
      "name": 9,
      "type": "bookmarks",
      "panel": "BookmarksPanel",
      "lockedPanel": false,
      "bookmarks": true
    },
    {
      "cookieStoreId": "firefox-default",
      "icon": "...",
      "name": 7,
      "type": "default",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "noEmpty": false
    },
    {
      "cookieStoreId": "firefox-container-1",
      "color": "...",
      "icon": "...",
      "name": 8,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-2",
      "color": "...",
      "icon": "...",
      "name": 4,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    },
    {
      "cookieStoreId": "firefox-container-6",
      "color": "...",
      "icon": "...",
      "name": 9,
      "type": "ctx",
      "panel": "TabsPanel",
      "lockedTabs": false,
      "lockedPanel": false,
      "proxy": null,
      "proxified": false,
      "noEmpty": false,
      "includeHostsActive": false,
      "includeHosts": "",
      "excludeHostsActive": false,
      "excludeHosts": ""
    }
  ],
  "cssVars": {
    "nav_btn_width": "30px"
  },
  "sidebarCSSLen": 29,
  "windows": [
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 403,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 11,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 3,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "minimized",
      "incognito": false,
      "tabsCount": 46,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 411,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    },
    {
      "state": "normal",
      "incognito": false,
      "tabsCount": 7,
      "logs": [
        "[INFO] Settings loaded",
        "[INFO] Containers loaded",
        "[INFO] Tabs loaded",
        "[INFO] Keybindings loaded",
        "[INFO] Styles loaded",
        "[INFO] Permissions loaded",
        "[INFO] Favicons loaded"
      ]
    }
  ],
  "bookmarks": {
    "bookmarksCount": 413,
    "foldersCount": 25,
    "separatorsCount": 2,
    "maxDepth": 3
  }
}
</pre>

</details>
