### ISSUE TITLE
How to solve the white screen problem?

### ISSUE THREAD

**Issue by i110077** [mbnuqw/sidebery#969]
Every time I open it, it flashes a white screen, very annoying, is there a way to solve it?
Thanks

**Comment by Zabooby** [comment]
Also getting this issue, maybe this closed issue from the TST repo might help? 

piroor/treestyletab/issues/1714

**Comment by mbnuqw** [comment]
This should be fixed (or at least improved) in the next beta release, though it's still possible to get that contrast flash depending on system theme, Appearance config of Firefox (Automatic/Light/Dark) and Firefox theme used.

**Comment by Zabooby** [comment]
For more context, I have dark mode set in both Windows and Firefox settings and have set Firefox theme in the Sidebery settings to match my theme, will this specific config be fixed in the new beta? 

Unrelated questions: 
How do I hide the recently closed tabs button at the bottom of the panel (I'm new to Sidebery and vertical tabs in general)? 

Why is the version on the Firefox store is so old?

**Comment by mbnuqw** [comment]
`will this specific config be fixed in the new beta?`
Yes, it should, as long as system theme and Firefox are both dark/light. But I didn't test Windows specifically, so there is still some probability for that issue.

`How do I hide the recently closed tabs button at the bottom of the panel (I'm new to Sidebery and vertical tabs in general)?`
In b31 you need to use this custom CSS (In Sidebery editor):
```css
.TabsPanel .bottom-bar {
  display: none;
}
```
In b32 you will be able to turn it off in settings.

`Why is the version on the Firefox store is so old?`
Because sidebery was rewritten from the ground (mostly) and I wanted to experiment with some ideas...(this is a project for fun after all) But, v5 is almost ready. The rough roadmap looks like that: Performance optimizations, at least major bug fixes, tests, docs and I'll update stable version. There will no new big features until v5.

**Comment by Zabooby** [comment]
Thanks for the detailed response, as a uni student I know that Sidebery will be a game changer for me!

**Comment by mbnuqw** [comment]
Should be fixed in v5.0.0. Feel free to reopen if not.

**Comment by MrSmoke** [comment]
I'm still getting this issue
- Firefox 118.0.1
- Fedora 38
- Sideberry 5.0.0

[Screencast from 2023-10-09 17-12-43.webm](https://github.com/mbnuqw/sidebery/assets/709976/33741a96-db4c-4354-b672-41194da907c3)

**Comment by alixTal** [comment]
https://github.com/mbnuqw/sidebery/assets/90468198/1b9114d9-737f-4b07-8b1c-44a008029553

same issue, firefox 122, Sidebery 5, macos.

**Comment by pnd280** [comment]
this is still happening on (both v5.2.0 and the latest v5.2.0.9)
- 128.3.0
- 130.0
- 132.0a1

Windows 11 Version 23H2 (OS Build 22631.4037)

**Comment by sibber5** [comment]
using (in userChrome.css)
```
#sidebar,
#sidebar-box,
#sidebar-header,
#sidebar-content,
#webextpanels-window,
#webext-panels-browser {
   background: var(--bg) !important;
   background-color: var(--bg) !important;
   color: var(--bg) !important;
}
```

reduced the flashing to one color: (0.2x speed)

https://github.com/user-attachments/assets/595f71f6-ceba-479b-8ad5-e511879a21c2
